from nginx:1.15

RUN addgroup --gid 3000 --system app \
    && adduser --uid 3000 --system --disabled-login --disabled-password --gid 3000 app \
    && usermod -a -G app nginx \
    && mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/site.conf.disabled \
    && set -ex \
    && { \
        echo 'server {'; \
        echo '    listen       80;'; \
        echo '    server_name  localhost;'; \
        echo '    root         /var/www;'; \
        echo '    index        index.html;'; \
        echo '    error_page   500 502 503 504  /50x.html;'; \
        echo '    location = /50x.html {'; \
        echo '        root   /usr/share/nginx/html;'; \
        echo '    }'; \
        echo ''; \
        echo '    location = /favicon.ico {'; \
        echo '    }'; \
        echo ''; \
        echo '}'; \
       } | tee /etc/nginx/conf.d/site.conf
